---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

title: Homelab
statusStyle: dot
headerStyle: clean
background:
  image: /images/background.webp
  blur: md
  opacity: 25
color: slate
theme: dark

hideVersion: true

logpath: /logs
instanceName: ${instanceName}

layout:
  Media:
    icon: mdi-movie
  Management:
    icon: mdi-folder
  Tools:
    icon: mdi-toolbox