---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: false
    nodes:
      show: false