prowlarr:
  hostname: localhost
  port: 9696
  protocol: http
  api_key: ${prowlarr_api_key}

  settings:
    apps:
      delete_unmanaged: true
      definitions:
          Sonarr:
            type: sonarr
            instance_name: Sonarr
            prowlarr_url: http://localhost:9696
            base_url: http://localhost:8989
            sync_level: full-sync
          Radarr:
            type: radarr
            instance_name: Radarr
            prowlarr_url: http://localhost:9696
            base_url: http://localhost:7878
            sync_level: full-sync

