api:
  dashboard: true
  insecure: true

providers:
  file:
    directory: /etc/traefik/providers
    watch: false

entrypoints:
  web:
    address: ":80"

log:
  level: DEBUG
  filePath: /logs/traefik.log