api:
  dashboard: true
  insecure: true

providers:
  file:
    directory: /etc/traefik/providers
    watch: false
  kubernetesIngress:
    namespaces:
      - ${namespace}

entrypoints:
  web:
    address: ":80"

log:
  level: INFO
